#RunshellScript
#RunPowerShellScript

trigger:
- none

pool:
  vmImage: ubuntu-latest
  
variables:
  -name: vm_name
  -value: "myVM"
  
  
steps:

- task: AzureCLI@2
  displayName: execute command inside vm
  inputs:
    azureSubscription: 'Azure subscription 1 (b0b4b5a1-15df-4090-9ade-a43bf67dbedb)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
#    inlineScript: 'az vm run-command invoke --command-id RunShellScript --name myVM -g myResourceGroup --scripts "PGPASSWORD=Admin12345 psql -h kashanpostgres.postgres.database.azure.com -p 5432 -U Kashan@kashanpostgres -v -d testde2 -f bkup.sql"'

    inlineScript: 'az vm run-command invoke --command-id RunShellScript --name myVM -g myResourceGroup --scripts "PGPASSWORD=Admin12345 createdb -h kashanpostgres.postgres.database.azure.com -p 5432 -U Kashan@kashanpostgres testdb" "pg_dump --help" \n "PGPASSWORD=Admin12345 pg_dump -h kashanpostgres.postgres.database.azure.com -p 5432 -U Kashan@kashanpostgres -v -d IDigital365 -f bkup.sql" "PGPASSWORD=Admin12345 psql -h kashanpostgres.postgres.database.azure.com -p 5432 -U Kashan@kashanpostgres -v -d testde3 -f bkup.sql"'
